[ci] Created deploy to github scripts

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -62,6 +62,9 @@ jobs:
             echo "PLAYGROUND_UI_VERSION='$PLAYGROUND_UI_VERSION'" >> $BASH_ENV
             echo "MELLIS_VERSION='$MELLIS_VERSION'" >> $BASH_ENV
             echo "MELLIS_PYTHON3_VERSION='$MELLIS_PYTHON3_VERSION'" >> $BASH_ENV
+            
+            # Get commit range of build
+            $SCRIPTS/get_commit_range.sh
 
       - run:
           name: Test Unity project
@@ -90,79 +93,121 @@ jobs:
           when: always
           command: $SCRIPTS/slack_notify_testrunner.sh
 
-  # deploy-github-webgl:
-  #   working_directory: ~/repo
+  build-webgl:
+    working_directory: ~/repo
     
-  #   environment:
-  #     SCRIPTS: /root/repo/ci/scripts/
+    environment:
+      SCRIPTS: /root/repo/ci/scripts/
 
-  #   docker:
-  #     - image: zifrose/unity3d-webgl
+    docker:
+      - image: zifrose/unity3d-webgl
 
-  #   steps:
-  #     # Checkout repo -> ~/repo
-  #     - checkout
+    steps:
+      # Checkout repo -> ~/repo
+      - checkout
 
-  #     - run:
-  #         name: Enable permissions on scripts
-  #         command: chmod +x $SCRIPTS/**.sh -v
+      - run:
+          name: Enable permissions on scripts
+          command: chmod +x $SCRIPTS/**.sh -v
+    
+      # TODO: Use cache from build-test
+      # TODO: Create artifact
 
-  #     - run:
-  #         name: Add GPG login to git
-  #         command: $SCRIPTS/git_login.sh
+  deploy-github-release:
+    working_directory: ~/repo
+    
+    environment:
+      SCRIPTS: /root/repo/ci/scripts/
 
-  #     - run:
-  #         name: Checkout deployment branch (→ ~/upm)
-  #         command: |
-  #           : ${GITHUB_PUBLISH_BRANCH:=upm}
-  #           : ${CIRCLE_REPOSITORY_URL?}
+    docker:
+      - image: zifrose/unity3d-webgl
 
-  #           git clone $CIRCLE_REPOSITORY_URL --single-branch --branch $GITHUB_PUBLISH_BRANCH ~/upm
-  #           code=$?
-  #           ls ~/upm
-  #           exit $code
+    steps:
+      # Checkout repo -> ~/repo
+      - checkout
+
+      - run:
+          name: Enable permissions on scripts
+          command: chmod +x $SCRIPTS/**.sh -v
             
-  #     - run:
-  #         name: Obtaining Playground UI version
-  #         command: |
-  #           shopt -s globstar
+      - run:
+          name: Obtaining Playground UI version
+          command: |
+            shopt -s globstar
 
-  #           # Get versions
-  #           PLAYGROUND_CARCONTROLLER_VERSION="$($SCRIPTS/get_attr_version.sh ~/repo/Assets/**/CarControllerAssemblyInfo.cs)"
-  #           echo ">>> Using Playground Car-Controller v$PLAYGROUND_CARCONTROLLER_VERSION"
+            # Get versions
+            PLAYGROUND_CARCONTROLLER_VERSION="$($SCRIPTS/get_attr_version.sh ~/repo/Assets/**/CarControllerAssemblyInfo.cs)"
+            echo ">>> Using Playground Car-Controller v$PLAYGROUND_CARCONTROLLER_VERSION"
 
-  #           # Save to environment
-  #           echo "PLAYGROUND_CARCONTROLLER_VERSION='$PLAYGROUND_CARCONTROLLER_VERSION'" >> $BASH_ENV
+            # Save to environment
+            echo "PLAYGROUND_CARCONTROLLER_VERSION='$PLAYGROUND_CARCONTROLLER_VERSION'" >> $BASH_ENV
 
-  #     - run:
-  #         name: Prepare files for deployment
-  #         command: |
-  #           : ${PLAYGROUND_CARCONTROLLER_VERSION?}
+            # Get commit range of build
+            $SCRIPTS/get_commit_range.sh
 
-  #           echo ">>> Update version package.json to '$PLAYGROUND_CARCONTROLLER_VERSION'"
-  #           echo "$(jq ".version=\"$PLAYGROUND_CARCONTROLLER_VERSION\"" ~/upm/package.json)" > ~/upm/package.json
-  #           echo
+      - run:
+          name: Cancel if tag already exists
+          command: |
+            PROJECT_VERSION="${PLAYGROUND_CARCONTROLLER_VERSION?}"
 
-  #           $SCRIPTS/move_upm_files.sh ~/repo ~/upm
-  #           $SCRIPTS/generate_metafiles.sh ~/upm
+            if ! [ "$PROJECT_VERSION" ]
+            then
+                echo "No project version. Throwing."
+                exit 1
+            fi
 
-  #     - run:
-  #         name: Deploy to UPM branch
-  #         command: $SCRIPTS/deploy_upm.sh ~/repo ~/upm
+            TAG="v$PROJECT_VERSION"
 
-  #     - run:
-  #         name: Setting Failure Condition
-  #         command: echo 'export BUILD_STATUS="fail"' >> $BASH_ENV
-  #         when: on_fail
-  #     - run:
-  #         name: Setting Success Condition
-  #         command: echo 'export BUILD_STATUS="success"' >> $BASH_ENV
-  #         when: on_success
+            if [ "$(git tag -l "$TAG")" ]
+            then
+                echo "Tag \"$TAG\" already exists. Aborting."
+
+                : ${CIRCLE_BUILD_NUM?}
+                : ${CIRCLE_API_KEY?}
+                : ${CIRCLE_BUILD_URL?}
+                : ${CIRCLE_PROJECT_USERNAME?}
+                : ${CIRCLE_PROJECT_REPONAME?}
+
+                $SCRIPTS/slack_deploy_no_new_tag.sh
+                curl -X POST -u "$CIRCLE_API_KEY:" https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BUILD_NUM/cancel
+
+                # Sleep to await the cancel
+                sleep 10s
+            else
+                echo "Tag \"$TAG\" does not exist. Free to go!"
+            fi
+            
+      - run:
+          name: Add GPG login to git
+          command: $SCRIPTS/git_login.sh
+
+      - run:
+          name: Download artifacts
+          command: |
+            $SCRIPTS/circle_download_artifacts.sh ~/artifacts
+
+      - run:
+          name: Publish release
+          command: $SCRIPTS/deploy_upm.sh ~/repo ~/upm
+
+      - run:
+          name: Cancel release
+          command: $SCRIPTS/deploy_github_cancel.sh
+          when: on_fail
+
+      - run:
+          name: Setting Failure Condition
+          command: echo 'export BUILD_STATUS="fail"' >> $BASH_ENV
+          when: on_fail
+      - run:
+          name: Setting Success Condition
+          command: echo 'export BUILD_STATUS="success"' >> $BASH_ENV
+          when: on_success
           
-  #     - run:
-  #         name: Send Slack notification
-  #         when: always
-  #         command: $SCRIPTS/slack_notify_github_deploy.sh
+      - run:
+          name: Send Slack notification
+          when: always
+          command: $SCRIPTS/slack_deploy_github.sh
 
 workflows:
   version: 2.1
@@ -181,10 +226,10 @@ workflows:
             branches:
               <<: *WORKFLOW_BUILD_TEST_DEPLOY_FILTER
 
-      # - deploy-github-webgl:
-      #     requires:
-      #       - build-test
+      - deploy-github-release:
+          requires:
+            - build-webgl
             
-      #     filters:
-      #       branches:
-      #         <<: *WORKFLOW_BUILD_TEST_DEPLOY_FILTER
+          filters:
+            branches:
+              <<: *WORKFLOW_BUILD_TEST_DEPLOY_FILTER
